### ISSUE TITLE
❓ Using forked package

### ISSUE THREAD

**Issue by behroozbc** [Rikj000/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject#1]
hi 
why you using this package 
https://github.com/Rikj000/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject/blob/cfdf59c99b78909b40ac863eebe0910faed21c63/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject.csproj#L11 
and not this https://github.com/Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting

**Comment by Rikj000** [comment]
When I was working on this example project there wasn't an official v0.3.16 available yet,
thus I went with the fork of it
