### ISSUE TITLE
📝 Docs - Return `byte` not `string`

### ISSUE THREAD

**Issue by behroozbc** [Rikj000/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject#2]
hi 
this byte payload and not string 
https://github.com/Rikj000/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject/blob/cfdf59c99b78909b40ac863eebe0910faed21c63/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject/Controllers/Mqtt/ExampleController.cs#L58

**Comment by Rikj000** [comment]
Nice catch! :mechanical_arm:
Docs updated in commit: https://github.com/Rikj000/Saunter-MQTTnet-AspNet5-AttributeRouting-ExampleProject/commit/89736ffeb4796f25e49929e193f6a6482b3ca760
